### ISSUE TITLE
Line buffering does not work when fed two lines at once

### ISSUE THREAD

**Issue by moshez** [markrwilliams/hypotalk#1]
```
>>> import line_buffering
>>> a=line_buffering.BuffersLines()
>>> a.feed('hello\ngoodbye\n')
>>> a.readline()
'hello\n'
>>> a.readline()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line_buffering.py", line 21, in readline
    raise NoLine
line_buffering.NoLine
>>> 
```

**Comment by markrwilliams** [comment]
yup, i forgot to push the sliced chunk back into the buffer:
https://github.com/markrwilliams/hypotalk/blob/master/line_buffering.py#L23
should read something like
```python
        line, nl, chunk = b"".join(line_chunks).partition(b"\n")
        self.buffer.insert(i, chunk)
        return line + nl
```
for extra credit, write a hypothesis test that exposes this ;)
